version: "3.3"
services:
  profiles:
    image: ${DOCKER_REGISTRY:-docker-registry.dev.mtg-api.com}/mtg/profiles:latest
    ports:
      - "1337:80"
      - "4000:4000"
    expose:
      - '4000'
    environment:
      - LOG_LEVEL=DEBUG
      - PORT_EXTERNAL=4000
      - LOG_PRETTY_PRINT=true
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=identity
      - AWS_SECRET_ACCESS_KEY=credential
      - DYNAMODB_ENDPOINT=localstack:4566
      - DYNAMODB_USE_LOCAL=true
      - COUNTRY_CONFIG_FILE_SYSTEM=local
      - SITEMAPS_FROM_CMS_SERVICE=true
    depends_on:
      - profiles-dynamodb-provisioning

  localstack:
    image: localstack/localstack:latest
    logging:
      driver: none
    hostname: localstack
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=identity
      - AWS_SECRET_ACCESS_KEY=credential
      - DEBUG=trace
      - SERVICES=dynamodb
      - LOCALSTACK_HOSTNAME=localstack
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - '4566:4566'
    expose:
      - '4566'
    labels:
      - com.mtg.waitfor.ports=4566

  profiles-dynamodb-provisioning:
    image: ${DOCKER_REGISTRY:-docker-registry.dev.mtg-api.com}/mtg/profiles-dynamodb-provisioning:latest
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=identity
      - AWS_SECRET_ACCESS_KEY=credential
    depends_on:
      - localstack